name: 'PhpMetrics Action'
description: 'Static analysis tool for PHP'
branding:
  icon: 'check-square'
  color: 'blue'
inputs:
  folder:
    description: 'Folder to be scanned'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
